POST https://f2e.dxy.net/mock-api/open/api/autoImport/5e070cdf06057b983417fdbb
Content-Type: application/json

{
  "importType": 2,
  "token": "dee736269a542059340b789aa69fca7513e00517",
  "userToken": "8342727f4d01d8511ddcd887c61abf9e",
  "devUrl": "www.dxy.net/bbs/newweb-test",
  "prodUrl": "www.dxy.cn/bbs/newweb",
  "isOrigin": true,
  "json": {
    "name": "测试导入接口name",
    "desc": "测试导入接口desc",
    "url": "/testImport/:id",
    "options": {
      "method": "get",
      "params": {
        "query": [
          {
            "key": "queryname",
            "required": true,
            "type": "string",
            "comment": ""
          }
        ],
        "body": [
          {
            "key": "bodyname",
            "required": true,
            "type": "string",
            "comment": "",
            "params": [
              {
                "key": "bodyname",
                "required": true,
                "type": "string"
              }
            ],
            "items": {
              "type": "object",
              "params": []
            }
          }
        ]
      },
      "response": [
        {
          "status": 200,
          "statusText": "",
          "params": [
            {
              "key": "repname",
              "type": "string",
              "comment": "",
              "params": [],
              "items": []
            }
          ]
        }
      ]
    }
  }
}