POST https://f2e.dxy.net/mock-api/open/api/autoImport/5e070cdf06057b983417fdbb
Content-Type: application/json

{
  "importType": 2,
  "token": "dee736269a542059340b789aa69fca7513e00517",
  "userToken":"8342727f4d01d8511ddcd887c61abf9e",
  "devUrl": "https://www.dxy.net/bbs",
  "prodUrl": "https://www.dxy.cn/bbs",
  "isOrigin": false,
  "json": {
    "basePath": "/",
    "paths": {
      "/test02": {
        "get": {
          "consumes": [
            "application/json"
          ],
          "description": "",
          "operationId": "",
          "parameters": [
            {
              "in": "query",
              "name": "a",
              "required": true,
              "type": "number"
            },
            {
              "in": "query",
              "name": "b",
              "required": false,
              "type": "number"
            }
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "properties": {
                  "code": {
                    "description": "",
                    "example": "success",
                    "mock": {
                      "mock": "0"
                    },
                    "type": "number"
                  },
                  "errMsg": {
                    "description": "错误信息",
                    "mock": {
                      "mock": "param error"
                    },
                    "type": "string"
                  },
                  "data": {
                    "type": "array",
                    "items": {
                      "description": "",
                      "type": "number"
                    }
                  }
                },
                "required": [],
                "title": "com.example.plugin.controller.Result",
                "type": "object"
              }
            }
          },
          "summary": "测试01111",
          "tags": []
        }
      }
    },
    "schemes": [
      "http",
      "https"
    ],
    "swagger": "2.0"
  },
  "apis": [
    false
  ]
}